remote_theme: smartclean/just-the-docs
logo: "https://www.smartclean.io/matrix/images/matrix-logo-2.png"
aux_links:
  "Homepage":
    - "https://www.smartclean.io"
gh_edit_link: false
footer_content: "All rights reserved © SmartClean Technologies Pte. Ltd. 2022"
